[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pyam3"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pyserial-asyncio",
    "crcmod",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pyam3*"]

[tool.setuptools.package-data]
"pyam3.protocol" = ["commands.json"]
